APP_NAME = "eating-meeting-api"

ZOMATO_API_KEY="f2d1ff84780572cc58732047ec778dce"
ZOMATO_BASE_URL="https://developers.zomato.com"
ZOMATO_API_PREFIX="/api/v2.1"
ZOMATO_URL = ZOMATO_BASE_URL + ZOMATO_API_PREFIX
ZOMATO_AUTHENTICATION_HEADER="user-key"