import os
APP_NAME = "eating-meeting-api"

ZOMATO_API_KEY=os.environ['ZOMATO_API_KEY']
ZOMATO_BASE_URL="https://developers.zomato.com"
ZOMATO_API_PREFIX="/api/v2.1"
ZOMATO_URL = ZOMATO_BASE_URL + ZOMATO_API_PREFIX
ZOMATO_AUTHENTICATION_HEADER="user-key"

POSTGRES_USER = os.environ["POSTGRES_USER"]
POSTGRES_PASSWORD = os.environ["POSTGRES_PASSWORD"]

POSTGRES_HOST = os.environ["POSTGRES_HOST"]
POSTGRES_DBNAME = os.environ["POSTGRES_DBNAME"]